service: mongo-pool-8

provider:
  name: aws
  runtime: nodejs8.10
  timeout: 10

functions:
  hello:
    handler: handler.hello
    events:
      - http: GET hello
    environment:
      MONGODB_URI: ${env:SLS_MONGO_URI}
